[0m22:05:58.123037 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3EE6ABBD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3EE736E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3EE6A9FD0>]}


============================== 22:05:58.136695 | e4a3c6e4-4630-41b8-9259-c6570028df76 ==============================
[0m22:05:58.136695 [info ] [MainThread]: Running with dbt=1.6.0
[0m22:05:58.138695 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\lenovo\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run --models staging', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:05:58.140694 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\lenovo\fintech-ai-platform\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:05:58.144692 [debug] [MainThread]: Command `dbt run` failed at 22:05:58.144692 after 0.15 seconds
[0m22:05:58.148696 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3EEACF4D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3EEACEC10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F3EE6A1710>]}
[0m22:05:58.150703 [debug] [MainThread]: Flushing usage events
[0m20:41:05.404179 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8BD9CDDD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8BB2084D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8BDCE50D0>]}


============================== 20:41:05.412178 | 1e0ded06-709d-4336-8f3d-d3af0d57a003 ==============================
[0m20:41:05.412178 [info ] [MainThread]: Running with dbt=1.6.0
[0m20:41:05.413778 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\lenovo\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --models marts', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:41:05.414780 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\lenovo\fintech-ai-platform\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:41:05.416776 [debug] [MainThread]: Command `dbt run` failed at 20:41:05.416776 after 0.08 seconds
[0m20:41:05.417891 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8BDCD8450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8BDC96510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A8BD9BC390>]}
[0m20:41:05.418779 [debug] [MainThread]: Flushing usage events
[0m00:28:49.725198 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3FB698B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3FB3C4650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3FB37A810>]}


============================== 00:28:49.738857 | 0cb18ddf-1035-4141-8dac-84d0a51987ef ==============================
[0m00:28:49.738857 [info ] [MainThread]: Running with dbt=1.6.0
[0m00:28:49.741860 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\lenovo\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m00:28:49.743858 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\lenovo\fintech-ai-platform\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:28:49.745866 [debug] [MainThread]: Command `dbt run` failed at 00:28:49.745866 after 0.08 seconds
[0m00:28:49.746866 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3FB397C90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3FB0B2B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B3FB0B2D90>]}
[0m00:28:49.747856 [debug] [MainThread]: Flushing usage events
